export { default as Home } from './home'
export { default as Browse } from './browse'
export { default as SignIn } from './signin'
export { default as SignUp } from './signup'
export { default as Account } from './account'
export { default as Plans } from './plans'
export { default as Contact } from './contact';
export { default as FAQ } from './faq';
export { default as Corporate } from './corporate';
export { default as Original } from './original';
export { default as Terms } from './terms';
export { default as Privacy } from './privacy';
export { default as Legal } from './legal';
